version: "3.9"

services:
  sonar:
    image: sonarqube:9.9.5-community
    container_name: sonarqube
    env_file:
      - path: .env
        required: true
    volumes:
      - ./conf:/opt/sonarqube/conf:rw
      - ./data:/opt/sonarqube/data:rw
      - ./extensions:/opt/sonarqube/extensions:rw
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9000", "||", "exit", "1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2GB
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: sonarqube-db
    environment:
      - TZ=Asia/Jakarta
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonar"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: